///////////// INGREDIENTS LISTS /////////////

// Rivenlands
const rivenlandsCommon =
    {
        "Black Pepper": {"Fortify Constitution": 3, "Fortify Constitution": 3, "Resist Fire": 2, "Weakness to Fire": 1, "Resist Acid": 1},
        "Bolean Violet": { "Resist Force": 4, "Fortify Sleight of Hand": 4, "Fortify Persuasion": 1, "Resist Psychic": 1, "Fortify Dexterity": 1},
        "Brittlebush Flower": { "Weakness to Piercing": 2, "Resist Acid": 3, "Fortify Spell Strength": 3, "Resist Necrotic": 2, "Damage (Fire)": 1},
        "Brittlebush Resin": { "Weakness to Acid": 3, "Weakness to Cold": 3, "Fortify Stealth": 2, "Weakness to Piercing": 2, "Fortify Sleight of Hand": 1},
        "Butterfly Moss": { "Weakness to Poison": 4, "Fortify Armor": 4, "Fortify Charisma": 1, "Fortify Investigation": 2, "Fortify Speed": 1},
        "Cardamom": { "Resist Radiant": 4, "Damage (Lightning)": 5, "Fortify History": 2, "Fortify Speed": 1, "Damage (Poison)": 1},
        "Cinnamon": { "Weakness to Lightning": 4, "Fortify Constitution": 4, "Resist Lightning": 1, "Fortify History": 1, "Damage (Cold)": 2},
        "Cloves": { "Resist Lightning": 3, "Fortify Wisdom": 3, "Weakness to Fire": 3, "Resist Necrotic": 1, "Damage (Force)": 1},
        "Colic Yellowcress ": { "Invisibility": 3, "Weakness to Force": 4, "Weakness to Thunder": 2, "Weakness to Piercing": 1, "Fortify Wisdom": 2},
        "Comb Mint": { "Invisibility": 4, "Fortify Constitution": 4, "Fortify Intelligence": 2, "Fortify Intelligence": 1, "Heal": 1},
        "Coriander (Leaves)": { "Heal": 4, "Fortify Investigation": 4, "Fortify Constitution": 2, "Resist Cold": 2, "Damage (Acid)": 1},
        "Coriander (Seeds)": { "Weakness to Acid": 3, "Fortify Persuasion": 3, "Fortify Performance": 2, "Fortify Speed": 2, "Damage (Poison)": 3},
        "Cork Tree Bark": { "Fortify Medicine": 3, "Damage (Necrotic)": 3, "Damage (Acid)": 1, "Fortify Nature": 1, "Damage (Necrotic)": 1},
        "Crow Hood": { "Damage (Psychic)": 3, "Invisibility": 2, "Fortify Spell DC": 1, "Resist Acid": 2, "Damage (Necrotic)": 2},
        "Cumin (Seeds)": { "Damage (Fire)": 3, "Weakness to Psychic": 3, "Damage (Acid)": 1, "Fortify Spell DC": 4, "Fortify Sleight of Hand": 1},
        "Desert Shrub": { "Fortify Constitution": 3, "Damage (Psychic)": 4, "Fortify Alchemy": 2, "Resist Necrotic": 2, "Fortify Animal Handling": 1},
        "Eucalyptus (Oil)": { "Resist Fire": 2, "Fortify Charisma": 4, "Fortify Perception": 2, "Weakness to Force": 1, "Damage (Thunder)": 1},
        "Eucalyptus (Gum)": { "Damage (Acid)": 5, "Damage (Lightning)": 3, "Fortify Constitution": 1, "Damage (Cold)": 2, "Fortify Strength": 2},
        "Eucalyptus (Leaves)": { "Fortify Dexterity": 3, "Guided Strike": 3, "Fortify Persuasion": 1, "Fortify Deception": 2, "Fortify Insight": 3},
        "Eucalyptus (Seeds)": { "Fortify Acrobatics": 5, "Resist Necrotic": 3, "Fortify Sleight of Hand": 1, "Resist Poison": 2, "Resist Poison": 2},
        "Fire Itchweed": { "Weakness to Bludgeoning": 3, "Weakness to Piercing": 3, "Fortify Intelligence": 2, "Fortify Speed": 2, "Fortify History": 1},
        "Four-Leafed Colwort": { "Resist Necrotic": 2, "Heal": 3, "Fortify Armor": 2, "Resist Psychic": 2, "Fortify Acrobatics": 1},
        "Frukmoot": { "Damage (Radiant)": 3, "Fortify Constitution": 3, "Damage (Fire)": 1, "Fortify Health": 1, "Damage (Force)": 2},
        "Ginger (Root)": { "Weakness to Cold": 4, "Heal": 3, "Fortify Medicine": 2, "Fortify Armor": 2, "Resist Psychic": 2},
        "Jasmine (Flower)": { "Fortify Athletics": 4, "Fortify History": 4, "Weakness to Bludgeoning": 1, "Weakness to Fire": 2, "Fortify Spell DC": 1},
        "Life's Collard": { "Damage (Thunder)": 3, "Fortify Health": 3, "Fortify Health": 2, "Weakness to Psychic": 1, "Fortify Investigation": 2},
        "Lotus (Petals)": { "Fortify Stealth": 3, "Fortify Constitution": 4, "Weakness to Radiant": 2, "Fortify Investigation": 1, "Weakness to Necrotic": 1},
        "Lotus (Seeds)": { "Weakness to Fire": 4, "Fortify Dexterity": 3, "Waterbreathing": 2, "Fortify Athletics": 2, "Resist Necrotic": 2},
        "Mango (Leaves)": { "Resist Lightning": 4, "Fortify History": 3, "Resist Lightning": 1, "Fortify Initiative": 1, "Resist Thunder": 1},
        "Mango (Taproot)": { "Damage (Radiant)": 4, "Weakness to Piercing": 3, "Weakness to Poison": 1, "Fortify Initiative": 2, "Fortify Initiative": 1},
        "Marigold (Flower)": { "Resist Psychic": 3, "Fortify Insight": 4, "Weakness to Cold": 1, "Resist Radiant": 1, "Fortify Athletics": 2},
        "Marigold (Leaves)": { "Fortify Sleight of Hand": 4, "Fortify Arcana": 4, "Fortify Constitution": 2, "Fortify Intelligence": 1, "Weakness to Necrotic": 2},
        "Mustard (Flower)": { "Invisibility": 4, "Resist Thunder": 4, "Fortify Speed": 1, "Clairvoyance": 1, "Fortify Investigation": 2},
        "Mustard (Greens)": { "Damage (Lightning)": 4, "Fortify Perception": 3, "Damage (Psychic)": 1, "Damage (Thunder)": 2, "Fortify Persuasion": 1},
        "Mustard (Seeds)": { "Waterbreathing": 4, "Fortify Arcana": 4, "Resist Cold": 1, "Resist Lightning": 1, "Resist Radiant": 1},
        "Nutmeg (Oil)": { "Resist Psychic": 3, "Damage (Radiant)": 4, "Resist Fire": 2, "Damage (Lightning)": 1, "Damage (Lightning)": 2},
        "Nutmeg (Seed)": { "Fortify Nature": 3, "Fortify Nature": 4, "Fortify Strength": 1, "Fortify Survival": 2, "Fortify Performance": 1},
        "Radiant Azolla": { "Regain Spell Slot": 3, "Weakness to Piercing": 4, "Fortify Religion": 1, "Resist Poison": 2, "Fortify Persuasion": 1},
        "Red Chili (Seeds)": { "Damage (Psychic)": 3, "Fortify Nature": 5, "Damage (Psychic)": 2, "Fortify Sleight of Hand": 1, "Fortify Speed": 2},
        "Wall Snakeberry": { "Fortify Wisdom": 3, "Weakness to Force": 3, "Weakness to Lightning": 2, "Fortify Intimidation": 1, "Fortify Performance": 3}
    };

const rivenlandsUncommon =
    {
        "Aloe Vera": { "Fortify Wisdom": 5, "Weakness to Thunder": 5, "Weakness to Acid": 1, "Fortify History": 2, "Resist Fire": 1},
        "Ash Gallberry": { "Fortify Speed": 6, "Damage (Thunder)": 5, "Fortify Strength": 3, "Damage (Thunder)": 2, "Weakness to Acid": 1},
        "Baby Zinnia": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Black Salt": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Buzzard Bile": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Corea Mint": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Dead Sage": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Dog Tongue": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Fennec Fox Droppings": { "Damage (Lightning)": 5, "Damage (Cold)": 5, "Damage (Fire)": 2, "Fortify Medicine": 1, "Damage (Fire)": 1},
        "Giant Lizard Venom": { "Damage (Psychic)": 6, "Resist Acid": 6, "Fortify Insight": 2, "Fortify Strength": 1, "Invisibility": 3},
        "Marsupial Wolf Blood": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Noxious Laurel": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Ocort": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Orange Thyme": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Pale Penny Gilliflower": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Phoenix Briar": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Pocan Hemp": { "Clairvoyance": 6, "Fortify Insight": 5, "Damage (Necrotic)": 1, "Fortify Strength": 1, "Resist Radiant": 1},
        "Prickly Cane": { "Weakness to Piercing": 6, "Waterbreathing": 6, "Resist Thunder": 1, "Fortify Alchemy": 2, "Fortify History": 1},
        "Serpent Rye": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Shivering Laurel": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Snage": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2},
        "Two-Tongued Scorpion Tail": { "Damage (Lightning)": 7, "Damage (Thunder)": 5, "Resist Psychic": 3, "Fortify Wisdom": 1, "Damage (Lightning)": 1},
        "Viper Venom": { "Weakness to Thunder": 5, "Fortify Spellcasting": 5, "Damage (Cold)": 1, "Fortify Arcana": 1, "Damage (Force)": 2}
    };

const rivenlandsRare =
    {
        "Blackheart Flower": { "Fortify Strength": 8, "Damage (Psychic)": 8, "Fortify Sleight of Hand": 4, "Fortify Medicine": 5, "Fortify Health": 2},
        "Burrowing Vee Spider": { "Fortify Constitution": 8, "Fortify Arcana": 8, "Weakness to Cold": 5, "Fortify Perception": 5, "Damage (Fire)": 1},
        "Jee Redzin Scorpion Eggs": { "Resist Psychic": 8, "Fortify Arcana": 8, "Fortify Investigation": 5, "Weakness to Force": 5, "Fortify Athletics": 1},
        "Kreetlee Leaves": { "Fortify Sleight of Hand": 8, "Fortify Nature": 8, "Fortify Stealth": 4, "Fortify Insight": 4, "Waterbreathing": 1},
        "Olaart Buds": { "Weakness to Psychic": 7, "Weakness to Slashing": 8, "Damage (Poison)": 4, "Damage (Necrotic)": 5, "Fortify Investigation": 1},
        "Smouse Oil": { "Resist Cold": 7, "Weakness to Necrotic": 8, "Resist Fire": 5, "Resist Thunder": 5, "Damage (Necrotic)": 1},
        "Wretch Salts": { "Weakness to Bludgeoning": 7, "Guided Strike": 8, "Damage (Lightning)": 5, "Resist Cold": 4, "Fortify Intimidation": 1},
        "Zettin Seeds": { "Damage (Acid)": 7, "Damage (Poison)": 7, "Fortify Alchemy": 5, "Damage (Lightning)": 4, "Regain Spell Slot": 2}
    };

// Midlands
const midlandsCommon =
    {
        "Alaclose": { "Fortify Armor": 3, "Fortify Armor": 4, "Damage (Lightning)": 1, "Fortify Charisma": 2, "Resist Fire": 1},
        "Black Centipede": { "Fortify History": 3, "Fortify Spell Strength": 3, "Weakness to Necrotic": 1, "Resist Acid": 1, "Weakness to Force": 1},
        "Blood Ants": { "Fortify Speed": 4, "Resist Acid": 3, "Fortify Charisma": 2, "Damage (Radiant)": 2, "Fortify Religion": 1},
        "Bloody Rose": { "Damage (Acid)": 4, "Fortify Armor": 3, "Disguise Self": 1, "Regain Spell Slot": 2, "Fortify Animal Handling": 1},
        "Blue Damselfly": { "Fortify Armor": 4, "Fortify Deception": 4, "Waterbreathing": 1, "Fortify Insight": 1, "Fortify Stealth": 1},
        "Blue Grama Grass": { "Fortify Health": 4, "Fortify Deception": 5, "Fortify Wisdom": 2, "Fortify Nature": 2, "Fear": 1},
        "Bluestem Grass": { "Fortify Spell DC": 4, "Resist Necrotic": 4, "Fortify Religion": 2, "Weakness to Thunder": 1, "Resist Fire": 1},
        "Breidlace Mushrooms": { "Fortify Medicine": 3, "Resist Radiant": 4, "Invisibility": 2, "Fortify Religion": 1, "Damage (Acid)": 1},
        "Bumblebee": { "Damage (Force)": 4, "Fortify Speed": 3, "Resist Force": 1, "Weakness to Bludgeoning": 1, "Resist Radiant": 1},
        "Burr Peas": { "Damage (Lightning)": 4, "Weakness to Cold": 3, "Weakness to Piercing": 1, "Damage (Fire)": 2, "Fortify Deception": 1},
        "Cardinal Egg": { "Resist Lightning": 4, "Clairvoyance": 5, "Fortify Strength": 3, "Weakness to Radiant": 1, "Weakness to Cold": 2},
        "Carpet Moss": { "Guided Strike": 4, "Weakness to Thunder": 3, "Damage (Thunder)": 2, "Fortify Spell DC": 2, "Damage (Fire)": 2},
        "Chregon": { "Fortify Perception": 4, "Fortify Survival": 3, "Damage (Fire)": 4, "Weakness to Bludgeoning": 1, "Weakness to Slashing": 1},
        "Cornied Gell Seeds": { "Weakness to Poison": 3, "Fortify Spell Strength": 3, "Weakness to Cold": 1, "Heal": 2, "Resist Lightning": 1},
        "Daisy": { "Fortify Religion": 3, "Resist Necrotic": 4, "Resist Psychic": 1, "Invisibility": 2, "Damage (Cold)": 2},
        "Dradbush": { "Fortify Stealth": 3, "Fortify Nature": 4, "Fortify Insight": 1, "Fortify History": 1, "Fortify Perception": 1},
        "Dragonfly": { "Fortify Investigation": 3, "Fortify Deception": 4, "Damage (Acid)": 3, "Weakness to Bludgeoning": 1, "Fortify Health": 1},
        "Dranied Wall Kerries": { "Fortify Stealth": 3, "Weakness to Cold": 3, "Weakness to Lightning": 2, "Fortify Medicine": 1, "Weakness to Psychic": 2},
        "Eagle Eyes": { "Weakness to Cold": 3, "Damage (Fire)": 3, "Resist Lightning": 1, "Fortify Perception": 1, "Damage (Thunder)": 2},
        "Ethalned": { "Resist Poison": 3, "Weakness to Fire": 4, "Damage (Cold)": 1, "Resist Psychic": 2, "Weakness to Radiant": 1},
        "Field Drerries": { "Damage (Fire)": 4, "Weakness to Force": 4, "Fortify Arcana": 1, "Regain Spell Slot": 2, "Fortify Arcana": 2},
        "Fire Lily": { "Fortify Alchemy": 4, "Weakness to Cold": 4, "Fortify Armor": 3, "Weakness to Cold": 1, "Regain Spell Slot": 2},
        "Fleabane": { "Weakness to Thunder": 4, "Fortify Wisdom": 4, "Damage (Radiant)": 1, "Fortify Strength": 2, "Fortify Religion": 1},
        "Green Salamander": { "Damage (Necrotic)": 4, "Fortify Health": 4, "Fortify Persuasion": 2, "Damage (Cold)": 2, "Weakness to Radiant": 1},
        "Green Violet": { "Resist Lightning": 3, "Damage (Force)": 4, "Heal": 2, "Fortify Performance": 3, "Disguise Self": 2},
        "Gretted Saffron": { "Weakness to Necrotic": 4, "Fortify Wisdom": 4, "Weakness to Force": 1, "Damage (Necrotic)": 1, "Weakness to Slashing": 2},
        "Idarreef": { "Resist Psychic": 4, "Weakness to Slashing": 4, "Fortify Survival": 1, "Weakness to Acid": 2, "Fortify Religion": 1},
        "Lenessied Posy": { "Fortify Health": 4, "Fortify Persuasion": 3, "Fortify Dexterity": 3, "Fortify Dexterity": 2, "Weakness to Necrotic": 1},
        "Lime Flower": { "Damage (Force)": 3, "Weakness to Thunder": 3, "Fortify Dexterity": 1, "Fortify Speed": 1, "Fortify Performance": 2},
        "Lira's Bell": { "Fortify Religion": 3, "Fortify Sleight of Hand": 4, "Regain Spell Slot": 2, "Weakness to Necrotic": 1, "Heal": 2},
        "Meddeweed": { "Invisibility": 3, "Fortify Arcana": 3, "Fortify Arcana": 2, "Weakness to Psychic": 4, "Weakness to Necrotic": 1},
        "Milkweed": { "Guided Strike": 4, "Heal": 3, "Damage (Fire)": 4, "Fortify Speed": 3, "Weakness to Necrotic": 1},
        "Nettle": { "Weakness to Force": 3, "Resist Psychic": 3, "Fortify Nature": 2, "Fortify Alchemy": 1, "Guided Strike": 2},
        "Nightshade": { "Fortify Health": 4, "Fortify Intelligence": 4, "Resist Fire": 1, "Weakness to Cold": 1, "Fortify Nature": 2},
        "Oak Blood": { "Weakness to Acid": 4, "Weakness to Psychic": 4, "Weakness to Acid": 1, "Fortify Arcana": 2, "Weakness to Necrotic": 2},
        "Oakheart": { "Fortify Armor": 4, "Clairvoyance": 4, "Resist Fire": 1, "Fortify Stealth": 2, "Fortify Sleight of Hand": 1},
        "Orange Damselfly": { "Damage (Acid)": 4, "Weakness to Psychic": 3, "Fortify Performance": 1, "Damage (Lightning)": 2, "Resist Necrotic": 1},
        "Orange Dragon Tongue": { "Fortify Survival": 3, "Disguise Self": 3, "Resist Acid": 1, "Disguise Self": 2, "Weakness to Psychic": 3},
        "Osie Swinies": { "Fortify Intelligence": 4, "Resist Thunder": 3, "Fortify Performance": 3, "Damage (Cold)": 1, "Resist Fire": 1},
        "Painted Butterfly": { "Fortify Strength": 3, "Fortify Athletics": 3, "Damage (Fire)": 1, "Damage (Psychic)": 1, "Weakness to Radiant": 2},
        "Pelor's Staff": { "Fortify Spell DC": 4, "Weakness to Psychic": 3, "Fortify Insight": 3, "Fortify Dexterity": 1, "Fortify Strength": 2},
        "Perennial Skale-Leaf": { "Fortify Investigation": 4, "Regain Spell Slot": 3, "Damage (Force)": 1, "Resist Force": 1, "Damage (Psychic)": 1},
        "Pink Braries": { "Fortify Constitution": 4, "Fortify Deception": 3, "Damage (Force)": 1, "Fortify Stealth": 2, "Weakness to Thunder": 2},
        "Plainned Froa": { "Disguise Self": 3, "Damage (Poison)": 4, "Damage (Thunder)": 2, "Damage (Cold)": 2, "Invisibility": 2},
        "Prass Lily": { "Resist Radiant": 3, "Weakness to Cold": 4, "Fortify Survival": 2, "Resist Psychic": 4, "Guided Strike": 3},
        "Purple Dragon Tongue": { "Weakness to Slashing": 3, "Fortify Intimidation": 4, "Weakness to Cold": 1, "Weakness to Acid": 2, "Fortify Speed": 2},
        "Rattlesnake Rattle": { "Damage (Thunder)": 4, "Fortify Spell Strength": 3, "Fortify Spell Strength": 1, "Weakness to Poison": 1, "Resist Necrotic": 3},
        "Red Centipede": { "Fortify Spell Strength": 4, "Fortify Persuasion": 4, "Fortify Athletics": 1, "Fortify Initiative": 2, "Weakness to Cold": 1},
        "Red Dragon Tongue": { "Fortify Spell Strength": 3, "Weakness to Acid": 3, "Fear": 1, "Weakness to Cold": 3, "Resist Lightning": 2},
        "Red Salamander": { "Resist Radiant": 3, "Fortify Alchemy": 4, "Damage (Thunder)": 2, "Fortify Acrobatics": 2, "Fortify Spell DC": 1},
        "Rose Elder": { "Resist Radiant": 4, "Resist Necrotic": 4, "Fortify Acrobatics": 2, "Fortify Intimidation": 1, "Regain Spell Slot": 1},
        "Sapphire Butterfly": { "Damage (Necrotic)": 4, "Fortify Insight": 4, "Weakness to Psychic": 2, "Resist Fire": 1, "Fortify Spell DC": 1},
        "Skelly Poplar Sap": { "Weakness to Cold": 4, "Fortify Religion": 4, "Fortify Sleight of Hand": 2, "Fortify Deception": 2, "Damage (Thunder)": 1},
        "Spotted Bard Egg": { "Damage (Thunder)": 4, "Weakness to Bludgeoning": 3, "Damage (Thunder)": 1, "Fortify Survival": 1, "Fortify Religion": 1},
        "Spotted Orra": { "Fortify Wisdom": 4, "Fortify Athletics": 5, "Fortify Strength": 1, "Fortify Nature": 1, "Regain Spell Slot": 1},
        "Starry Cammonies": { "Fortify Initiative": 3, "Fortify Charisma": 4, "Fortify Deception": 2, "Weakness to Thunder": 1, "Waterbreathing": 1},
        "Starweed": { "Waterbreathing": 4, "Fortify Acrobatics": 4, "Damage (Cold)": 1, "Clairvoyance": 1, "Damage (Fire)": 1},
        "Tanglewood Vine": { "Resist Necrotic": 3, "Fortify Insight": 3, "Resist Lightning": 1, "Weakness to Fire": 2, "Fortify Performance": 1},
        "Thedren Berries": { "Fortify Persuasion": 3, "Fortify Animal Handling": 4, "Weakness to Bludgeoning": 1, "Weakness to Force": 2, "Resist Thunder": 2},
        "Torchbug": { "Damage (Thunder)": 3, "Fortify Performance": 4, "Fortify Nature": 2, "Resist Thunder": 1, "Fortify Deception": 1},
        "Ulied Blackberries": { "Fortify Intimidation": 4, "Fortify Perception": 3, "Fortify Wisdom": 1, "Resist Force": 2, "Fortify Survival": 1},
        "Warbler Egg": { "Resist Lightning": 5, "Fortify Spell Strength": 3, "Clairvoyance": 2, "Damage (Acid)": 1, "Fortify Athletics": 2},
        "Whispering Moths": { "Fortify Arcana": 4, "Damage (Poison)": 3, "Fortify History": 1, "Damage (Lightning)": 1, "Fortify Religion": 2},
        "White Honeysuckle": { "Fortify Dexterity": 3, "Weakness to Cold": 3, "Fortify Health": 1, "Damage (Lightning)": 3, "Weakness to Cold": 1},
        "Witch's Claw": { "Fortify Speed": 4, "Fortify Religion": 3, "Damage (Necrotic)": 2, "Weakness to Acid": 1, "Resist Thunder": 1},
        "Wren Egg": { "Damage (Psychic)": 4, "Fortify Spell Strength": 3, "Fortify Performance": 1, "Weakness to Piercing": 1, "Damage (Acid)": 1},
        "Yellow Dragon Tongue": { "Fortify Athletics": 4, "Fortify Charisma": 4, "Resist Thunder": 2, "Fortify Intimidation": 1, "Fear": 3},
        "Yetted Clornfeather": { "Fortify Insight": 3, "Resist Radiant": 3, "Fortify Sleight of Hand": 1, "Fortify Survival": 3, "Damage (Thunder)": 1}
    };

const midlandsUncommon =
    {
	"Ashy Butterfly": { "Fortify History": 6, "Damage (Lightning)": 6, "Fortify Investigation": 1, "Weakness to Piercing": 1, "Damage (Fire)": 1},
	"Belas Web": { "Fortify Animal Handling": 6, "Fortify Deception": 6, "Resist Acid": 2, "Fortify Survival": 2, "Resist Force": 2},
	"Bowret Flies": { "Fortify Constitution": 6, "Weakness to Radiant": 6, "Weakness to Psychic": 2, "Guided Strike": 1, "Fortify Athletics": 2},
	"Brass Trumpet Mushroom": { "Fortify Charisma": 7, "Damage (Fire)": 5, "Fortify Dexterity": 1, "Damage (Fire)": 3, "Clairvoyance": 1},
	"Devil's Daisy": { "Clairvoyance": 5, "Resist Necrotic": 5, "Invisibility": 2, "Damage (Necrotic)": 1, "Weakness to Acid": 1},
	"Dret Cap": { "Fortify Strength": 5, "Weakness to Necrotic": 7, "Fortify Acrobatics": 1, "Fortify Armor": 1, "Damage (Poison)": 1},
	"Enphrine": { "Fortify Alchemy": 5, "Fortify Wisdom": 5, "Weakness to Bludgeoning": 1, "Heal": 2, "Weakness to Bludgeoning": 2},
	"Exoria": { "Resist Force": 5, "Weakness to Poison": 5, "Fortify Spell DC": 1, "Fortify Arcana": 2, "Weakness to Psychic": 2},
	"Flying Peonies": { "Weakness to Thunder": 6, "Fortify Sleight of Hand": 5, "Fortify Athletics": 2, "Resist Psychic": 1, "Fortify Wisdom": 2},
	"Golden Tree Coral": { "Fortify History": 4, "Weakness to Psychic": 5, "Clairvoyance": 3, "Fortify Acrobatics": 2, "Damage (Thunder)": 1},
	"Green Warbler Egg": { "Resist Necrotic": 5, "Damage (Thunder)": 6, "Disguise Self": 3, "Resist Fire": 1, "Resist Thunder": 1},
	"Jem's Lemons": { "Damage (Necrotic)": 5, "Fortify Spell Strength": 5, "Resist Thunder": 2, "Clairvoyance": 2, "Resist Fire": 2},
	"Knitted Lilac": { "Fortify Perception": 6, "Weakness to Necrotic": 6, "Weakness to Necrotic": 4, "Resist Poison": 2, "Clairvoyance": 1},
	"Lorex Crystals": { "Fortify Armor": 6, "Damage (Poison)": 5, "Resist Necrotic": 1, "Damage (Cold)": 2, "Resist Necrotic": 3},
	"Marbled Dragonfly": { "Fortify Religion": 5, "Damage (Necrotic)": 5, "Fortify Spell Strength": 1, "Fortify Health": 1, "Resist Radiant": 2},
	"Pin Berries": { "Fortify Nature": 5, "Fortify Sleight of Hand": 5, "Fortify Arcana": 1, "Fortify Persuasion": 1, "Weakness to Radiant": 1},
	"Rainbow Dragonfly": { "Fortify Charisma": 5, "Damage (Necrotic)": 4, "Fortify Animal Handling": 1, "Fortify Athletics": 1, "Fortify Performance": 2},
	"Seizeberry": { "Disguise Self": 6, "Resist Fire": 5, "Damage (Radiant)": 2, "Weakness to Psychic": 2, "Invisibility": 2},
	"Sighing Orchid": { "Weakness to Force": 6, "Weakness to Poison": 5, "Fortify Wisdom": 1, "Weakness to Necrotic": 2, "Fortify Intelligence": 3},
	"Swilling Cress": { "Invisibility": 5, "Damage (Poison)": 7, "Resist Force": 2, "Fortify Persuasion": 2, "Fortify Spell DC": 1},
	"Threncarrot": { "Weakness to Poison": 6, "Resist Radiant": 6, "Resist Poison": 3, "Damage (Cold)": 2, "Weakness to Psychic": 2},
	"Velvet Rose": { "Fortify History": 5, "Fear": 6, "Damage (Necrotic)": 1, "Fortify Speed": 1, "Fortify Health": 2},
	"Weeping Laceflower": { "Fortify Charisma": 5, "Fortify Sleight of Hand": 5, "Damage (Acid)": 2, "Regain Spell Slot": 1, "Weakness to Thunder": 1},
	"Yellowwood Vines": { "Resist Thunder": 7, "Fortify Perception": 7, "Weakness to Cold": 1, "Fortify Persuasion": 1, "Weakness to Slashing": 2}
};

const midlandsRare =
    {
        "Bloody Dragonfly": { "Weakness to Poison": 7, "Damage (Necrotic)": 7, "Fear": 4, "Weakness to Radiant": 5, "Resist Force": 2},
        "Glass Orchid": { "Fortify Strength": 7, "Weakness to Necrotic": 8, "Fortify Intimidation": 4, "Fortify Animal Handling": 4, "Resist Acid": 2},
        "Hauer Ants": { "Weakness to Acid": 8, "Fortify Animal Handling": 7, "Weakness to Bludgeoning": 5, "Fortify Religion": 4, "Damage (Psychic)": 2},
        "Jade Root": { "Weakness to Lightning": 7, "Fortify Nature": 7, "Weakness to Lightning": 4, "Fortify Intimidation": 4, "Damage (Necrotic)": 2},
        "Seelie Root": { "Damage (Fire)": 7, "Heal": 8, "Fortify Constitution": 4, "Fortify Speed": 5, "Weakness to Fire": 3},
        "Silver Skipper Wings": { "Fortify Armor": 7, "Damage (Thunder)": 7, "Damage (Lightning)": 5, "Weakness to Slashing": 4, "Damage (Radiant)": 2},
        "Three-Flowered Neetri": { "Fortify History": 7, "Fortify Wisdom": 8, "Fortify Insight": 5, "Resist Cold": 5, "Damage (Lightning)": 2},
        "White Blood Orchid": { "Resist Fire": 7, "Fortify Spell DC": 7, "Fortify Speed": 5, "Fortify Intelligence": 5, "Fortify Arcana": 2}
    };

// Chainlands
const chainlandsCommon =
    {
        "African Daisy": { "Fortify Intelligence": 4, "Damage (Radiant)": 4, "Damage (Fire)": 1, "Fortify Charisma": 1, "Weakness to Lightning": 2},
        "Bay Laurel Leaves": { "Guided Strike": 4, "Damage (Radiant)": 4, "Invisibility": 1, "Fortify Insight": 3, "Fortify Religion": 2},
        "Bear's Breech": { "Clairvoyance": 3, "Fortify Religion": 4, "Resist Lightning": 1, "Damage (Lightning)": 2, "Resist Poison": 2},
        "Blue Spire": { "Damage (Acid)": 3, "Weakness to Fire": 4, "Fortify Armor": 2, "Invisibility": 1, "Weakness to Fire": 1},
        "Broad Bean Roots": { "Weakness to Slashing": 4, "Fortify Health": 4, "Fortify Performance": 2, "Weakness to Acid": 2, "Weakness to Thunder": 1},
        "Cabbage Moth": { "Fortify Performance": 4, "Fortify Nature": 4, "Fortify Health": 1, "Damage (Psychic)": 2, "Regain Spell Slot": 1},
        "Chain Termites": { "Fortify Persuasion": 3, "Fortify Insight": 3, "Fear": 1, "Weakness to Lightning": 1, "Fortify Perception": 1},
        "Cherry Taproot": { "Resist Thunder": 3, "Weakness to Fire": 4, "Fortify Persuasion": 2, "Weakness to Bludgeoning": 1, "Fortify Persuasion": 4},
        "Creeping Fig": { "Fortify Medicine": 4, "Weakness to Thunder": 3, "Damage (Thunder)": 1, "Damage (Necrotic)": 1, "Heal": 1},
        "Cypress Sap": { "Resist Acid": 3, "Fortify Dexterity": 3, "Resist Necrotic": 1, "Fortify Insight": 2, "Fortify Insight": 2},
        "Cypress Taproot": { "Damage (Poison)": 3, "Weakness to Thunder": 5, "Fortify Wisdom": 1, "Fortify Acrobatics": 1, "Resist Thunder": 1},
        "Daffodil": { "Fortify Armor": 3, "Resist Poison": 4, "Guided Strike": 1, "Weakness to Necrotic": 1, "Weakness to Cold": 1},
        "Dancing Lavender": { "Weakness to Radiant": 3, "Fortify Performance": 3, "Weakness to Force": 1, "Fortify Performance": 2, "Fortify Investigation": 2},
        "Digger Wasp Thorax": { "Fortify Medicine": 3, "Fortify Intimidation": 3, "Resist Force": 1, "Fortify Intelligence": 1, "Fortify Survival": 2},
        "Dock Bug Legs": { "Weakness to Psychic": 3, "Fortify Stealth": 4, "Resist Force": 1, "Fortify Spell Strength": 2, "Fortify Nature": 1},
        "Dwarf Iris": { "Damage (Thunder)": 4, "Fortify Intimidation": 3, "Resist Psychic": 1, "Weakness to Poison": 2, "Fortify Strength": 3},
        "Fennel": { "Weakness to Slashing": 4, "Fortify Survival": 4, "Fortify Spell DC": 1, "Weakness to Psychic": 1, "Damage (Necrotic)": 1},
        "Field Mushroom": { "Weakness to Piercing": 4, "Weakness to Slashing": 4, "Resist Lightning": 3, "Fortify Perception": 2, "Guided Strike": 2},
        "Fig": { "Damage (Psychic)": 3, "Fortify Perception": 3, "Damage (Force)": 2, "Weakness to Acid": 2, "Heal": 3},
        "Frankicense": { "Fortify Persuasion": 3, "Weakness to Poison": 4, "Damage (Acid)": 2, "Damage (Cold)": 1, "Damage (Acid)": 1},
        "Gallic Rose": { "Fortify Nature": 3, "Weakness to Psychic": 3, "Fortify Spell Strength": 1, "Damage (Fire)": 1, "Fortify Spell DC": 1},
        "Green Tiger Beetle Thorax": { "Damage (Cold)": 3, "Regain Spell Slot": 4, "Fortify Medicine": 2, "Resist Thunder": 2, "Damage (Fire)": 1},
        "Grey-Leaved Euryops": { "Fortify Performance": 4, "Resist Thunder": 4, "Fortify Spell DC": 1, "Fortify Initiative": 1, "Fortify Nature": 2},
        "Heliotrope": { "Fortify Arcana": 3, "Resist Lightning": 3, "Invisibility": 1, "Fortify Speed": 1, "Damage (Fire)": 3},
        "Hemlock": { "Fortify Armor": 3, "Fortify Constitution": 4, "Fortify Animal Handling": 2, "Damage (Necrotic)": 3, "Weakness to Thunder": 1},
        "Hyacinth": { "Weakness to Radiant": 4, "Fortify Wisdom": 4, "Fortify Nature": 2, "Damage (Force)": 2, "Weakness to Fire": 2},
        "Juniper Berries": { "Damage (Poison)": 3, "Disguise Self": 4, "Resist Force": 2, "Clairvoyance": 2, "Weakness to Acid": 2},
        "Lamb's Ear": { "Heal": 3, "Invisibility": 4, "Weakness to Slashing": 1, "Guided Strike": 2, "Heal": 2},
        "Larkspur": { "Resist Radiant": 4, "Weakness to Force": 3, "Weakness to Bludgeoning": 3, "Resist Poison": 2, "Fortify Dexterity": 1},
        "Lavender Cotton": { "Resist Lightning": 3, "Resist Lightning": 4, "Fortify Speed": 2, "Weakness to Slashing": 1, "Fortify Survival": 1},
        "Manna Ash Flower": { "Fortify Constitution": 3, "Fortify Dexterity": 4, "Resist Lightning": 3, "Fortify Charisma": 1, "Heal": 1},
        "Manna Ash Taproot": { "Guided Strike": 4, "Fortify Spell Strength": 4, "Fortify Alchemy": 3, "Fortify Alchemy": 3, "Weakness to Fire": 3},
        "Martin's Spurge": { "Clairvoyance": 4, "Damage (Cold)": 4, "Resist Cold": 1, "Fortify Spell Strength": 1, "Fortify Strength": 2},
        "Midland Grasshopper Wings": { "Weakness to Lightning": 4, "Clairvoyance": 3, "Damage (Fire)": 1, "Damage (Radiant)": 2, "Weakness to Cold": 1},
        "Monk's Hood": { "Resist Necrotic": 4, "Fortify Athletics": 4, "Regain Spell Slot": 2, "Weakness to Fire": 2, "Damage (Force)": 1},
        "Myrrh": { "Weakness to Poison": 4, "Weakness to Necrotic": 3, "Resist Force": 3, "Fortify Health": 1, "Fortify Nature": 3},
        "Myrtle": { "Fortify Intimidation": 3, "Damage (Lightning)": 4, "Fortify Alchemy": 1, "Fortify Speed": 1, "Resist Psychic": 1},
        "Northern Star": { "Resist Radiant": 4, "Disguise Self": 3, "Fear": 1, "Fortify Intimidation": 2, "Fortify Initiative": 1},
        "Parsley": { "Damage (Psychic)": 4, "Fortify Dexterity": 4, "Fortify Investigation": 1, "Weakness to Fire": 2, "Fortify Wisdom": 1},
        "Pomegranate Root": { "Fortify Sleight of Hand": 4, "Fortify Performance": 3, "Regain Spell Slot": 1, "Fortify Health": 1, "Fortify Initiative": 1},
        "Purple Sage": { "Clairvoyance": 4, "Weakness to Bludgeoning": 5, "Fortify Acrobatics": 1, "Damage (Poison)": 2, "Damage (Thunder)": 1},
        "Red Poppy": { "Fortify Health": 3, "Fortify Initiative": 4, "Resist Acid": 3, "Damage (Fire)": 1, "Damage (Fire)": 1},
        "Rockrose": { "Resist Fire": 5, "Weakness to Poison": 4, "Fortify Strength": 1, "Fortify Wisdom": 2, "Fortify Perception": 2},
        "Rosemary": { "Weakness to Force": 4, "Weakness to Fire": 4, "Resist Cold": 2, "Fortify Stealth": 2, "Fortify Constitution": 3},
        "Saffron": { "Weakness to Fire": 3, "Fortify Insight": 3, "Weakness to Fire": 1, "Fortify Spell DC": 2, "Resist Thunder": 2},
        "Sage-Leaf Mullein": { "Fortify History": 3, "Fortify Sleight of Hand": 3, "Fortify Acrobatics": 1, "Fortify Strength": 1, "Fortify Alchemy": 2},
        "Silver Fir Cone": { "Fortify Medicine": 3, "Weakness to Thunder": 4, "Damage (Poison)": 2, "Disguise Self": 1, "Weakness to Necrotic": 1},
        "Spear Mint": { "Damage (Thunder)": 3, "Damage (Thunder)": 3, "Clairvoyance": 2, "Fortify Performance": 1, "Damage (Thunder)": 1},
        "Stonecrop": { "Fortify Animal Handling": 4, "Fortify Alchemy": 3, "Damage (Necrotic)": 1, "Damage (Necrotic)": 2, "Weakness to Cold": 1},
        "Strawflower": { "Resist Lightning": 4, "Weakness to Psychic": 3, "Resist Cold": 2, "Resist Radiant": 3, "Fortify Spell Strength": 1},
        "Sunrise Olives": { "Resist Psychic": 4, "Regain Spell Slot": 3, "Fortify Medicine": 1, "Fortify Intelligence": 2, "Regain Spell Slot": 1},
        "Sweet Iris": { "Fortify Performance": 2, "Fortify Spell Strength": 4, "Resist Psychic": 2, "Weakness to Force": 1, "Fortify History": 3},
        "Sweet Violet": { "Heal": 3, "Fortify Initiative": 3, "Fortify Charisma": 1, "Weakness to Acid": 1, "Disguise Self": 2},
        "Thorny Juniper Branch": { "Fortify Intimidation": 4, "Fortify Arcana": 4, "Resist Necrotic": 1, "Weakness to Bludgeoning": 1, "Fortify Charisma": 2},
        "Walnut Oil": { "Fortify Perception": 4, "Fortify Medicine": 3, "Weakness to Acid": 1, "Damage (Psychic)": 1, "Weakness to Poison": 2},
        "White Lily": { "Fortify Deception": 4, "Fortify Strength": 4, "Fortify Arcana": 1, "Fortify Arcana": 3, "Damage (Acid)": 2},
        "Wild Celery": { "Fortify Charisma": 3, "Weakness to Thunder": 3, "Fortify Investigation": 1, "Damage (Fire)": 1, "Damage (Cold)": 2},
        "Windflower": { "Resist Necrotic": 3, "Fortify Intimidation": 4, "Fortify Armor": 1, "Resist Cold": 1, "Weakness to Fire": 1},
        "Wisley Primrose": { "Fortify Animal Handling": 3, "Resist Radiant": 2, "Fortify Nature": 1, "Regain Spell Slot": 2, "Waterbreathing": 2},
        "Withy": { "Damage (Cold)": 4, "Invisibility": 3, "Weakness to Cold": 2, "Damage (Lightning)": 3, "Fortify Performance": 2},
        "Yarrow": { "Invisibility": 4, "Invisibility": 3, "Weakness to Psychic": 2, "Fortify Survival": 1, "Regain Spell Slot": 1},
        "Yellow Meadow Ant": { "Fortify Intimidation": 4, "Damage (Acid)": 2, "Invisibility": 1, "Fortify Spell DC": 2, "Fortify Stealth": 1}
    };

const chainlandsUncommon =
    {
        "Blooming Willoweed": { "Damage (Acid)": 6, "Fortify Intimidation": 5, "Weakness to Force": 1, "Damage (Psychic)": 2, "Fortify Alchemy": 2},
        "Blue Inkberry": { "Fortify Survival": 5, "Weakness to Piercing": 5, "Damage (Lightning)": 2, "Resist Acid": 2, "Invisibility": 2},
        "Bride-o'-the-Sea": { "Resist Cold": 6, "Damage (Force)": 6, "Damage (Necrotic)": 1, "Fortify Arcana": 2, "Fear": 1},
        "Bronze Dragonfly": { "Weakness to Psychic": 6, "Fortify Persuasion": 6, "Resist Cold": 1, "Weakness to Acid": 3, "Damage (Cold)": 1},
        "Corar Tortoise Eggs": { "Fortify Charisma": 5, "Fortify Intelligence": 5, "Fortify Speed": 2, "Fortify Intelligence": 2, "Damage (Poison)": 2},
        "Fire Salamander Tail": { "Fortify Dexterity": 7, "Fortify Performance": 5, "Fortify History": 2, "Fortify Spell DC": 1, "Fortify Dexterity": 2},
        "Ghostly Asphodel": { "Fortify Nature": 6, "Fortify Wisdom": 4, "Fortify Perception": 2, "Damage (Poison)": 1, "Weakness to Slashing": 2},
        "Horseshoe Bat Droppings": { "Fortify Performance": 5, "Weakness to Psychic": 5, "Fortify Strength": 2, "Damage (Fire)": 2, "Waterbreathing": 1},
        "Merchant's Orchid": { "Fortify Athletics": 6, "Fortify Investigation": 6, "Invisibility": 1, "Fortify Speed": 1, "Regain Spell Slot": 1},
        "Monk Seal Oil": { "Resist Thunder": 6, "Fortify Perception": 6, "Damage (Radiant)": 2, "Fortify Survival": 3, "Weakness to Lightning": 1},
        "Opium Poppy": { "Resist Poison": 6, "Damage (Cold)": 6, "Weakness to Force": 1, "Clairvoyance": 1, "Fortify Strength": 1},
        "Prickly Ivy": { "Fortify Intelligence": 7, "Fortify Sleight of Hand": 4, "Clairvoyance": 3, "Fortify Deception": 3, "Resist Lightning": 1},
        "Ruddy Toad Tongue": { "Fortify Health": 5, "Weakness to Thunder": 5, "Weakness to Necrotic": 1, "Fortify Intimidation": 2, "Resist Radiant": 1},
        "Salt Snail": { "Fortify Strength": 5, "Fortify Acrobatics": 7, "Resist Acid": 2, "Resist Poison": 1, "Resist Cold": 2},
        "Silene Flower Bud": { "Fortify Initiative": 4, "Resist Poison": 6, "Fortify Charisma": 3, "Fortify Health": 2, "Fortify Initiative": 2},
        "Slender Nightshade": { "Weakness to Bludgeoning": 5, "Fortify Arcana": 7, "Weakness to Fire": 1, "Weakness to Cold": 2, "Waterbreathing": 3},
        "Southern Dagger Juice": { "Fortify Armor": 6, "Fortify Nature": 7, "Damage (Poison)": 3, "Fortify Acrobatics": 1, "Weakness to Acid": 3},
        "Spindly Spurge": { "Fortify Survival": 6, "Resist Thunder": 6, "Fortify Charisma": 1, "Weakness to Lightning": 1, "Fortify Intimidation": 2},
        "Turtle Bile": { "Weakness to Cold": 6, "Weakness to Fire": 6, "Damage (Acid)": 1, "Damage (Fire)": 1, "Fortify Alchemy": 1},
        "Whistle Fern": { "Heal": 5, "Weakness to Radiant": 7, "Guided Strike": 2, "Damage (Psychic)": 1, "Fortify Investigation": 2},
        "Witching Vine": { "Fortify Health": 6, "Weakness to Force": 5, "Weakness to Lightning": 2, "Fortify Wisdom": 1, "Resist Psychic": 2}
    };

const chainlandsRare =
    {
        "Chromaflux Root": { "Fortify Acrobatics": 8, "Fortify Stealth": 8, "Invisibility": 4, "Fortify Sleight of Hand": 5, "Weakness to Lightning": 1},
        "Luth Pearls": { "Fortify Insight": 7, "Weakness to Poison": 8, "Fortify Intelligence": 5, "Resist Thunder": 4, "Resist Radiant": 3},
        "Shiftberry Juice": { "Fortify Alchemy": 7, "Waterbreathing": 7, "Fortify Initiative": 5, "Heal": 5, "Weakness to Radiant": 1},
        "Spinning Sand Wasp": { "Damage (Cold)": 8, "Fortify Religion": 7, "Weakness to Force": 4, "Clairvoyance": 4, "Fortify Persuasion": 3},
        "Volcanic Minerals": { "Fortify Investigation": 7, "Fortify Acrobatics": 7, "Fortify Spell Strength": 5, "Fortify Sleight of Hand": 6, "Resist Lightning": 1},
        "Wayward Keek": { "Damage (Fire)": 8, "Fortify Armor": 7, "Fortify Armor": 5, "Weakness to Poison": 5, "Resist Lightning": 2},
        "Wixia Fly": { "Resist Poison": 8, "Resist Psychic": 7, "Damage (Force)": 5, "Fortify Spell Strength": 5, "Fortify Investigation": 2}
    };

// North
const northCommon =
    {
        "Arctic Moss": { "Heal": 4, "Disguise Self": 4, "Damage (Poison)": 2, "Weakness to Piercing": 2, "Weakness to Poison": 1},
        "Arctic Willow": { "Weakness to Acid": 3, "Resist Acid": 4, "Fortify Athletics": 1, "Resist Psychic": 1, "Fortify Spell DC": 2},
        "Ashrett": { "Weakness to Acid": 4, "Resist Necrotic": 4, "Fortify Athletics": 1, "Fortify Initiative": 2, "Weakness to Cold": 2},
        "Aves Tulip": { "Fortify Investigation": 4, "Fortify Athletics": 4, "Fortify History": 3, "Fortify Athletics": 1, "Resist Psychic": 2},
        "Balsam Fir Root": { "Resist Poison": 3, "Fortify Stealth": 4, "Damage (Radiant)": 2, "Fortify Deception": 1, "Damage (Fire)": 2},
        "Barbed Huckleberry": { "Fortify Health": 4, "Weakness to Thunder": 4, "Fortify Sleight of Hand": 2, "Fortify Persuasion": 2, "Fortify Wisdom": 1},
        "Bearberry": { "Damage (Cold)": 4, "Fortify Nature": 4, "Fortify Survival": 1, "Resist Necrotic": 2, "Fortify Health": 1},
        "Black Spruce Cones": { "Weakness to Cold": 3, "Weakness to Acid": 3, "Damage (Fire)": 3, "Fortify Armor": 1, "Resist Radiant": 2},
        "Brebore": { "Resist Psychic": 4, "Damage (Cold)": 4, "Fortify Speed": 1, "Weakness to Poison": 2, "Damage (Force)": 2},
        "Calcereous Earth": { "Damage (Psychic)": 2, "Fortify Dexterity": 3, "Resist Force": 1, "Waterbreathing": 1, "Weakness to Force": 2},
        "Caribou Antlers": { "Fortify Stealth": 4, "Resist Acid": 5, "Damage (Cold)": 3, "Fortify Medicine": 3, "Fortify Constitution": 2},
        "Caribou Moss": { "Fortify Insight": 3, "Weakness to Necrotic": 3, "Weakness to Psychic": 1, "Fortify Athletics": 1, "Fortify Charisma": 2},
        "Cendenroot": { "Weakness to Force": 3, "Fortify Nature": 3, "Resist Psychic": 2, "Resist Thunder": 1, "Fortify Acrobatics": 1},
        "Cotton Grass": { "Fortify Arcana": 3, "Fortify Alchemy": 3, "Weakness to Necrotic": 2, "Fortify Constitution": 1, "Weakness to Fire": 1},
        "Cranberries": { "Fortify Stealth": 3, "Weakness to Thunder": 4, "Fortify Animal Handling": 1, "Fortify Survival": 1, "Fortify Intimidation": 2},
        "Daydreaming Willow Heart": { "Weakness to Piercing": 5, "Resist Psychic": 4, "Fortify Medicine": 2, "Weakness to Cold": 1, "Fortify Investigation": 2},
        "Diamond Leaf Willow Root": { "Damage (Force)": 3, "Fortify Insight": 4, "Fortify Intimidation": 1, "Weakness to Thunder": 2, "Damage (Necrotic)": 1},
        "Eagle Eyes": { "Weakness to Cold": 3, "Damage (Fire)": 3, "Resist Lightning": 1, "Fortify Perception": 1, "Damage (Thunder)": 2},
        "Easleyfol": { "Fortify Health": 4, "Weakness to Lightning": 3, "Weakness to Bludgeoning": 1, "Fortify Nature": 2, "Damage (Radiant)": 2},
        "Etherluse": { "Weakness to Cold": 4, "Fortify Survival": 4, "Waterbreathing": 1, "Clairvoyance": 2, "Fortify Stealth": 2},
        "Feddle's Tea": { "Fortify Intimidation": 4, "Resist Lightning": 4, "Damage (Lightning)": 2, "Heal": 1, "Fortify Deception": 3},
        "Fennenbore": { "Clairvoyance": 4, "Fortify Intelligence": 4, "Fortify Armor": 3, "Fortify Dexterity": 2, "Weakness to Piercing": 1},
        "Fireweed": { "Fortify Performance": 3, "Weakness to Slashing": 4, "Fortify Nature": 1, "Weakness to Slashing": 2, "Damage (Thunder)": 2},
        "Frost Cabbage": { "Resist Thunder": 4, "Fear": 4, "Weakness to Necrotic": 1, "Fortify Spell DC": 1, "Regain Spell Slot": 1},
        "Frost-Blooded Rose": { "Fortify Perception": 3, "Fortify Nature": 3, "Resist Thunder": 1, "Fortify Performance": 1, "Resist Radiant": 1},
        "Goat Horn": { "Resist Radiant": 3, "Damage (Thunder)": 3, "Weakness to Bludgeoning": 1, "Weakness to Bludgeoning": 2, "Weakness to Piercing": 2},
        "Green Alder Flowers": { "Weakness to Poison": 3, "Weakness to Cold": 3, "Guided Strike": 3, "Fortify Arcana": 1, "Resist Lightning": 1},
        "Grizzly Bear Claws": { "Resist Lightning": 3, "Invisibility": 4, "Damage (Fire)": 1, "Resist Force": 1, "Fortify Constitution": 2},
        "Ishren Buds": { "Resist Cold": 4, "Resist Force": 3, "Fortify Athletics": 1, "Fortify Spell DC": 2, "Fortify Religion": 2},
        "Isponder": { "Damage (Cold)": 3, "Resist Cold": 3, "Weakness to Poison": 2, "Fortify Dexterity": 1, "Fortify Dexterity": 1},
        "Ithroot": { "Weakness to Cold": 3, "Fortify Arcana": 4, "Resist Necrotic": 1, "Fortify Speed": 1, "Resist Radiant": 1},
        "Krillseed": { "Invisibility": 3, "Fortify History": 4, "Damage (Acid)": 2, "Damage (Psychic)": 2, "Fortify Medicine": 1},
        "Leaded Thorn": { "Damage (Fire)": 4, "Waterbreathing": 4, "Heal": 1, "Fortify Intimidation": 1, "Weakness to Thunder": 1},
        "Long-Eared Owl Claws": { "Fortify Arcana": 3, "Fortify Nature": 4, "Resist Psychic": 2, "Resist Fire": 1, "Resist Acid": 1},
        "Moon Slorn": { "Damage (Fire)": 3, "Resist Lightning": 3, "Damage (Poison)": 1, "Fortify Constitution": 2, "Damage (Force)": 3},
        "Mottled Trew": { "Fortify Armor": 3, "Resist Acid": 4, "Resist Radiant": 1, "Fortify Nature": 2, "Fortify Intelligence": 3},
        "Northern Amethyst": { "Damage (Cold)": 5, "Fortify Charisma": 3, "Fortify Persuasion": 2, "Weakness to Thunder": 1, "Fortify Spell DC": 3},
        "Ocksey Feek": { "Resist Thunder": 4, "Weakness to Acid": 4, "Fortify Survival": 1, "Resist Force": 1, "Fortify Animal Handling": 2},
        "Olafloer": { "Resist Acid": 4, "Regain Spell Slot": 4, "Fortify Animal Handling": 1, "Fortify Sleight of Hand": 2, "Guided Strike": 3},
        "Ornan Juniper": { "Weakness to Acid": 3, "Fortify Strength": 4, "Damage (Radiant)": 2, "Fortify Animal Handling": 3, "Fortify Alchemy": 2},
        "Oxender Pollen": { "Clairvoyance": 3, "Damage (Fire)": 3, "Fortify Investigation": 2, "Fortify Nature": 1, "Weakness to Acid": 1},
        "Paper Birch Sap": { "Fortify Stealth": 4, "Fortify Religion": 5, "Resist Fire": 1, "Resist Acid": 2, "Resist Lightning": 2},
        "Peat Moss": { "Damage (Acid)": 4, "Fortify Perception": 4, "Damage (Acid)": 2, "Heal": 2, "Weakness to Lightning": 2},
        "Pine Sap": { "Fortify Perception": 3, "Damage (Acid)": 4, "Fortify Charisma": 1, "Clairvoyance": 2, "Damage (Fire)": 1},
        "Platted Were": { "Damage (Cold)": 3, "Heal": 4, "Fortify Investigation": 1, "Fortify Persuasion": 2, "Regain Spell Slot": 2},
        "Pumniscus": { "Fortify Armor": 4, "Fortify Deception": 4, "Invisibility": 3, "Fortify History": 2, "Fortify Performance": 1},
        "Red Cedar Berry": { "Disguise Self": 4, "Damage (Force)": 4, "Weakness to Piercing": 3, "Damage (Necrotic)": 1, "Fear": 1},
        "Red Cedar Oil": { "Weakness to Force": 4, "Fortify Spell DC": 4, "Fortify Insight": 1, "Invisibility": 1, "Damage (Acid)": 3},
        "Sastery": { "Fortify Charisma": 3, "Clairvoyance": 4, "Fortify Intimidation": 1, "Disguise Self": 1, "Fortify Medicine": 1},
        "Seal Oil": { "Resist Cold": 3, "Fortify Persuasion": 3, "Fortify History": 1, "Fortify Investigation": 1, "Resist Poison": 2},
        "Sellfole Moss": { "Weakness to Fire": 4, "Resist Fire": 4, "Fortify Wisdom": 1, "Weakness to Thunder": 2, "Disguise Self": 2},
        "Sheep Laurel": { "Fortify Survival": 4, "Weakness to Cold": 3, "Heal": 1, "Regain Spell Slot": 1, "Damage (Psychic)": 2},
        "Silver Hood": { "Resist Acid": 3, "Weakness to Thunder": 4, "Weakness to Radiant": 3, "Fortify Insight": 2, "Resist Acid": 2},
        "Silverblood Willow": { "Damage (Necrotic)": 3, "Weakness to Fire": 3, "Resist Psychic": 3, "Resist Acid": 1, "Resist Necrotic": 1},
        "Sleepy Aconite": { "Waterbreathing": 3, "Weakness to Psychic": 3, "Damage (Thunder)": 3, "Weakness to Psychic": 3, "Weakness to Radiant": 2},
        "Sleepy Velberry": { "Fortify Performance": 4, "Heal": 3, "Fortify Initiative": 2, "Weakness to Lightning": 2, "Fortify Initiative": 1},
        "Spinsort": { "Fortify Speed": 4, "Weakness to Poison": 5, "Resist Necrotic": 1, "Fortify Arcana": 2, "Damage (Psychic)": 1},
        "Thettlecove": { "Invisibility": 4, "Fortify Animal Handling": 4, "Fear": 2, "Guided Strike": 1, "Fortify Charisma": 2},
        "Tinweed": { "Damage (Radiant)": 4, "Heal": 3, "Fortify Medicine": 1, "Weakness to Piercing": 1, "Weakness to Poison": 1},
        "Tritecress": { "Resist Thunder": 4, "Damage (Fire)": 4, "Weakness to Psychic": 1, "Fortify Constitution": 2, "Fortify Deception": 4},
        "Tufted Saxifrage": { "Damage (Cold)": 4, "Resist Cold": 4, "Fortify Animal Handling": 2, "Weakness to Bludgeoning": 1, "Weakness to Poison": 2},
        "Tundra Tea": { "Invisibility": 3, "Resist Cold": 3, "Resist Lightning": 1, "Fortify Wisdom": 1, "Weakness to Slashing": 2},
        "Weddenthistle": { "Guided Strike": 3, "Weakness to Piercing": 4, "Weakness to Piercing": 2, "Regain Spell Slot": 1, "Fortify Spell Strength": 1},
        "White Fir Seeds": { "Damage (Cold)": 3, "Fortify Animal Handling": 4, "Weakness to Acid": 2, "Fortify Armor": 1, "Fortify Perception": 2},
        "White Poplar Leaves": { "Weakness to Necrotic": 4, "Regain Spell Slot": 4, "Fortify Wisdom": 2, "Waterbreathing": 1, "Weakness to Bludgeoning": 2},
        "Wild Rose": { "Weakness to Fire": 4, "Weakness to Bludgeoning": 4, "Weakness to Thunder": 1, "Fortify Constitution": 1, "Fear": 2},
        "Woody Trenlen": { "Disguise Self": 3, "Damage (Cold)": 3, "Fortify Religion": 1, "Resist Necrotic": 2, "Regain Spell Slot": 1},
        "Wren Threstle": { "Damage (Acid)": 3, "Resist Radiant": 5, "Fortify Spell DC": 1, "Weakness to Radiant": 1, "Weakness to Psychic": 2}
    };

const northUncommon =
    {
        "Coddled Moss": { "Fortify Investigation": 5, "Weakness to Force": 6, "Fortify History": 2, "Fortify Persuasion": 2, "Fortify Stealth": 2},
        "Arctic Bumblebee": { "Fortify Athletics": 5, "Disguise Self": 6, "Clairvoyance": 2, "Damage (Fire)": 1, "Weakness to Fire": 2},
        "Bladed Clover": { "Fortify Insight": 6, "Damage (Lightning)": 5, "Resist Lightning": 2, "Disguise Self": 2, "Fortify Insight": 1},
        "Brekkenflies": { "Weakness to Bludgeoning": 5, "Guided Strike": 6, "Fortify Acrobatics": 1, "Fortify Speed": 2, "Fortify Investigation": 1},
        "Chelding Spoolweed": { "Weakness to Acid": 5, "Weakness to Cold": 6, "Fortify Deception": 2, "Resist Necrotic": 3, "Fortify Persuasion": 1},
        "Elvish Lace": { "Resist Force": 6, "Fortify Spell DC": 6, "Weakness to Poison": 1, "Weakness to Fire": 1, "Weakness to Necrotic": 2},
        "Eovos Stalk": { "Fortify Intelligence": 5, "Resist Psychic": 5, "Disguise Self": 1, "Fortify Nature": 1, "Resist Acid": 1},
        "Evean Dragonfly": { "Weakness to Fire": 6, "Fortify Alchemy": 6, "Weakness to Slashing": 1, "Damage (Cold)": 1, "Weakness to Necrotic": 2},
        "Frost-Blooded Rose": { "Fortify Spell Strength": 6, "Heal": 5, "Fortify Strength": 1, "Fortify Alchemy": 1, "Fortify Stealth": 3},
        "Giant Toe Mushrooms": { "Resist Acid": 5, "Fortify Health": 5, "Fear": 3, "Damage (Poison)": 1, "Resist Radiant": 1},
        "Glowing Knot": { "Guided Strike": 5, "Resist Necrotic": 4, "Fortify Athletics": 2, "Weakness to Thunder": 3, "Damage (Lightning)": 1},
        "Inky Dwarf Nettle ": { "Fortify Intimidation": 5, "Weakness to Lightning": 6, "Resist Cold": 1, "Fear": 2, "Damage (Lightning)": 2},
        "Merry Snitchgrass": { "Fortify Strength": 6, "Resist Thunder": 5, "Weakness to Bludgeoning": 2, "Fortify Perception": 1, "Resist Acid": 1},
        "Narwhal Horn": { "Resist Lightning": 5, "Fortify Insight": 6, "Clairvoyance": 2, "Fortify Survival": 1, "Weakness to Thunder": 1},
        "Nee-of-the-Mist": { "Waterbreathing": 6, "Damage (Lightning)": 6, "Fortify Insight": 1, "Resist Cold": 2, "Fortify Animal Handling": 3},
        "Pere Clover": { "Fortify Wisdom": 6, "Weakness to Radiant": 7, "Resist Necrotic": 1, "Fortify Dexterity": 1, "Fortify Perception": 1},
        "Purple Gretspear": { "Invisibility": 6, "Resist Radiant": 4, "Fortify Nature": 2, "Fortify Performance": 1, "Fortify Sleight of Hand": 2},
        "Quee's Mad Seeds": { "Fortify Deception": 6, "Weakness to Bludgeoning": 5, "Fortify Health": 2, "Weakness to Radiant": 1, "Invisibility": 2},
        "Speerel Leaf": { "Weakness to Poison": 6, "Weakness to Fire": 6, "Fear": 1, "Weakness to Slashing": 1, "Fortify Investigation": 1},
        "Spiraled Wormwood": { "Damage (Poison)": 4, "Damage (Acid)": 6, "Damage (Cold)": 1, "Weakness to Thunder": 2, "Damage (Lightning)": 1},
        "Struthenbug Thorax": { "Fortify Wisdom": 6, "Damage (Lightning)": 6, "Disguise Self": 1, "Regain Spell Slot": 2, "Damage (Psychic)": 1},
        "Thraceous Root": { "Resist Lightning": 5, "Fortify Acrobatics": 5, "Fortify Sleight of Hand": 1, "Fortify Stealth": 2, "Resist Poison": 2},
        "Tretted Kline": { "Fortify Survival": 6, "Resist Fire": 6, "Weakness to Poison": 1, "Fortify Perception": 3, "Fortify Athletics": 2},
        "Weeping Monk": { "Fortify Performance": 5, "Weakness to Cold": 6, "Fortify Persuasion": 1, "Fortify Nature": 1, "Weakness to Lightning": 2},
        "Winking Blairflower": { "Fortify Animal Handling": 5, "Fortify Investigation": 6, "Fortify Spell DC": 1, "Damage (Fire)": 1, "Weakness to Bludgeoning": 2},
        "Wiry Etch Orchid": { "Weakness to Cold": 5, "Resist Psychic": 6, "Resist Lightning": 3, "Fortify Persuasion": 1, "Damage (Necrotic)": 1},
        "Yeti Ants": { "Fortify Sleight of Hand": 4, "Fortify Nature": 7, "Fortify Investigation": 2, "Weakness to Acid": 3, "Fortify Intelligence": 3}
    };

const northRare =
    {
	"Black Soulshade": { "Fortify Intimidation": 7, "Damage (Poison)": 8, "Fortify Survival": 5, "Fortify History": 4, "Fortify Charisma": 2},
	"Blue-Blooded Rose": { "Damage (Radiant)": 8, "Fear": 8, "Resist Psychic": 5, "Resist Lightning": 4, "Fortify Stealth": 1},
	"Frost Kerrie Bulb": { "Resist Acid": 7, "Weakness to Piercing": 7, "Fortify Sleight of Hand": 5, "Damage (Force)": 5, "Weakness to Fire": 2},
	"Moonbug Thorax": { "Fortify Investigation": 8, "Damage (Cold)": 6, "Weakness to Thunder": 5, "Resist Necrotic": 4, "Fortify Spell DC": 1},
	"Paper Snow Lily": { "Resist Lightning": 8, "Fortify History": 7, "Fortify Stealth": 4, "Fortify Performance": 4, "Fortify Alchemy": 1},
	"Spitting Thistle": { "Weakness to Poison": 7, "Fortify Survival": 8, "Fortify Animal Handling": 4, "Fortify Stealth": 4, "Weakness to Psychic": 1},
	"Witch-Breath Grass": { "Damage (Necrotic)": 8, "Weakness to Necrotic": 7, "Fortify Sleight of Hand": 5, "Fortify Investigation": 5, "Fortify Medicine": 2}
};

// Eleon
const eleonCommon =
    {
        "Alpine Strawberry": { "Resist Fire": 4, "Weakness to Thunder": 3, "Weakness to Acid": 1, "Damage (Lightning)": 1, "Resist Thunder": 2},
        "Arctic Moss": { "Heal": 4, "Disguise Self": 4, "Damage (Poison)": 2, "Weakness to Piercing": 2, "Weakness to Poison": 1},
        "Balsam Fir Root": { "Resist Poison": 3, "Fortify Stealth": 4, "Damage (Radiant)": 2, "Fortify Deception": 1, "Damage (Fire)": 2},
        "Balsam Fir Sap": { "Fortify Nature": 3, "Fortify Alchemy": 4, "Resist Lightning": 3, "Resist Psychic": 1, "Fortify Constitution": 1},
        "Bearberry": { "Damage (Cold)": 4, "Fortify Nature": 4, "Fortify Survival": 1, "Resist Necrotic": 2, "Fortify Health": 1},
        "Birch Borer Thorax": { "Clairvoyance": 4, "Fortify Investigation": 4, "Damage (Force)": 3, "Damage (Force)": 2, "Fortify Strength": 1},
        "Black Spruce Cones": { "Weakness to Cold": 3, "Weakness to Acid": 3, "Damage (Fire)": 3, "Fortify Armor": 1, "Resist Radiant": 2},
        "Blanket Flower": { "Fortify Charisma": 4, "Weakness to Piercing": 3, "Weakness to Force": 1, "Fortify Speed": 1, "Fortify Medicine": 3},
        "Bleeding Heart": { "Fear": 3, "Guided Strike": 4, "Guided Strike": 1, "Fortify Medicine": 3, "Fortify Investigation": 2},
        "Blue Columbine": { "Guided Strike": 4, "Fortify Alchemy": 3, "Waterbreathing": 2, "Fortify Spell DC": 1, "Fortify Religion": 3},
        "Blue Ghost": { "Weakness to Fire": 3, "Fortify Spell DC": 5, "Damage (Acid)": 1, "Damage (Force)": 2, "Fortify Health": 2},
        "Blue-of-the-Skies": { "Disguise Self": 4, "Guided Strike": 2, "Resist Radiant": 1, "Fortify Armor": 2, "Fortify Stealth": 1},
        "Broadleaf Lupine": { "Weakness to Slashing": 3, "Resist Necrotic": 4, "Resist Acid": 2, "Fortify Sleight of Hand": 2, "Fortify Speed": 1},
        "Broadleaf Sedum": { "Weakness to Thunder": 4, "Fortify History": 3, "Resist Radiant": 3, "Resist Fire": 1, "Weakness to Fire": 2},
        "Calcereous Earth": { "Damage (Psychic)": 2, "Fortify Dexterity": 3, "Resist Force": 1, "Waterbreathing": 1, "Weakness to Force": 2},
        "Camass": { "Resist Fire": 3, "Weakness to Piercing": 3, "Fortify Persuasion": 1, "Fortify Athletics": 2, "Weakness to Poison": 2},
        "Caribou Moss": { "Fortify Insight": 3, "Weakness to Necrotic": 3, "Weakness to Psychic": 1, "Fortify Athletics": 1, "Fortify Charisma": 2},
        "Clenia Amorum": { "Weakness to Necrotic": 4, "Resist Cold": 3, "Fortify Charisma": 1, "Heal": 1, "Damage (Acid)": 1},
        "Clovian Butterfly": { "Fortify Religion": 4, "Fortify Animal Handling": 4, "Weakness to Bludgeoning": 1, "Fortify Armor": 2, "Weakness to Lightning": 1},
        "Cotton Grass": { "Fortify Arcana": 3, "Fortify Alchemy": 3, "Weakness to Necrotic": 2, "Fortify Constitution": 1, "Weakness to Fire": 1},
        "Cranberries": { "Fortify Stealth": 3, "Weakness to Thunder": 4, "Fortify Animal Handling": 1, "Fortify Survival": 1, "Fortify Intimidation": 2},
        "Dart Flower": { "Fortify Sleight of Hand": 4, "Weakness to Slashing": 4, "Fortify Sleight of Hand": 2, "Weakness to Radiant": 2, "Fortify Deception": 1},
        "Eagle Eyes": { "Weakness to Cold": 3, "Damage (Fire)": 3, "Resist Lightning": 1, "Fortify Perception": 1, "Damage (Thunder)": 2},
        "Eleonic Lygus": { "Resist Poison": 3, "Fortify Athletics": 4, "Weakness to Thunder": 3, "Fortify Sleight of Hand": 1, "Weakness to Slashing": 1},
        "Elven Strawberry": { "Fortify Intimidation": 4, "Fortify Spell Strength": 4, "Damage (Necrotic)": 2, "Damage (Psychic)": 2, "Resist Poison": 1},
        "Elvish Lotus": { "Clairvoyance": 3, "Fortify Performance": 3, "Fortify Acrobatics": 2, "Weakness to Cold": 1, "Fortify Alchemy": 3},
        "Fireweed": { "Fortify Performance": 3, "Weakness to Slashing": 4, "Fortify Nature": 1, "Weakness to Slashing": 2, "Damage (Thunder)": 2},
        "Floating Bell": { "Damage (Fire)": 3, "Fortify Religion": 3, "Fortify Medicine": 2, "Resist Thunder": 1, "Weakness to Bludgeoning": 1},
        "Florean Petals": { "Weakness to Necrotic": 3, "Fortify Acrobatics": 3, "Fortify Religion": 1, "Weakness to Thunder": 2, "Invisibility": 2},
        "Goat Horn": { "Resist Radiant": 3, "Damage (Thunder)": 3, "Weakness to Bludgeoning": 1, "Weakness to Bludgeoning": 2, "Weakness to Piercing": 2},
        "Goatsbeard": { "Fortify Nature": 4, "Fortify Alchemy": 4, "Resist Cold": 1, "Guided Strike": 1, "Weakness to Lightning": 2},
        "Grapeholly": { "Fear": 3, "Weakness to Lightning": 4, "Clairvoyance": 1, "Weakness to Lightning": 2, "Damage (Psychic)": 2},
        "Green Alder Flowers": { "Weakness to Poison": 3, "Weakness to Cold": 3, "Guided Strike": 3, "Fortify Arcana": 1, "Resist Lightning": 1},
        "Knight Moth": { "Fortify Acrobatics": 2, "Fortify Religion": 4, "Damage (Thunder)": 2, "Fortify Religion": 1, "Weakness to Acid": 3},
        "Lewisia": { "Weakness to Piercing": 3, "Damage (Lightning)": 3, "Fortify Dexterity": 1, "Resist Poison": 2, "Damage (Thunder)": 3},
        "Long-Eared Owl Claws": { "Fortify Arcana": 3, "Fortify Nature": 4, "Resist Psychic": 2, "Resist Fire": 1, "Resist Acid": 1},
        "Mela's Lily": { "Weakness to Necrotic": 3, "Weakness to Force": 4, "Invisibility": 1, "Resist Cold": 3, "Weakness to Radiant": 2},
        "Metrian Orchid": { "Damage (Radiant)": 3, "Fortify Alchemy": 5, "Damage (Force)": 2, "Fortify Intimidation": 2, "Resist Poison": 3},
        "Mornater Iris": { "Fortify Charisma": 4, "Weakness to Thunder": 4, "Resist Thunder": 1, "Fortify Insight": 1, "Fortify Insight": 1},
        "Mullberries": { "Damage (Force)": 4, "Fortify Religion": 4, "Fortify Acrobatics": 1, "Damage (Thunder)": 3, "Damage (Necrotic)": 1},
        "Mullberry Leaves": { "Weakness to Piercing": 3, "Damage (Psychic)": 4, "Weakness to Fire": 2, "Weakness to Bludgeoning": 1, "Resist Radiant": 2},
        "Night Star": { "Fear": 3, "Fortify Nature": 4, "Fortify Wisdom": 1, "Weakness to Cold": 1, "Weakness to Acid": 2},
        "Northern Trillium": { "Fortify Sleight of Hand": 4, "Clairvoyance": 3, "Damage (Psychic)": 2, "Damage (Psychic)": 1, "Damage (Acid)": 1},
        "Oso Berry": { "Weakness to Bludgeoning": 4, "Weakness to Thunder": 3, "Fortify Charisma": 3, "Fortify Wisdom": 3, "Fortify Sleight of Hand": 2},
        "Paper Birch Sap": { "Fortify Stealth": 4, "Fortify Religion": 5, "Resist Fire": 1, "Resist Acid": 2, "Resist Lightning": 2},
        "Peat Moss": { "Damage (Acid)": 4, "Fortify Perception": 4, "Damage (Acid)": 2, "Heal": 2, "Weakness to Lightning": 2},
        "Red Cedar Berry": { "Disguise Self": 4, "Damage (Force)": 4, "Weakness to Piercing": 3, "Damage (Necrotic)": 1, "Fear": 1},
        "Red Cedar Oil": { "Weakness to Force": 4, "Fortify Spell DC": 4, "Fortify Insight": 1, "Invisibility": 1, "Damage (Acid)": 3},
        "Redwood Sap": { "Fortify Initiative": 3, "Weakness to Bludgeoning": 4, "Fortify Speed": 2, "Resist Acid": 2, "Resist Fire": 3},
        "Renia's Bloom": { "Fortify Animal Handling": 4, "Fortify Athletics": 4, "Damage (Psychic)": 1, "Fortify Survival": 1, "Fortify Stealth": 2},
        "River Dragons": { "Fortify Medicine": 3, "Fortify Investigation": 4, "Resist Fire": 2, "Fortify Perception": 3, "Weakness to Radiant": 1},
        "River Lamprey Bile": { "Weakness to Poison": 3, "Fortify Wisdom": 3, "Fortify Constitution": 1, "Fortify Arcana": 2, "Fortify Investigation": 2},
        "River Lotus": { "Fortify Investigation": 3, "Weakness to Radiant": 4, "Fortify Acrobatics": 1, "Fortify Performance": 1, "Fortify History": 1},
        "Salmonberry": { "Damage (Thunder)": 4, "Fortify Performance": 4, "Resist Cold": 1, "Damage (Psychic)": 1, "Clairvoyance": 1},
        "Satin Flower": { "Clairvoyance": 3, "Fortify Arcana": 4, "Damage (Psychic)": 1, "Damage (Force)": 1, "Resist Fire": 2},
        "Sheep Laurel": { "Fortify Survival": 4, "Weakness to Cold": 3, "Heal": 1, "Regain Spell Slot": 1, "Damage (Psychic)": 2},
        "Shooting Star": { "Damage (Radiant)": 2, "Weakness to Thunder": 4, "Disguise Self": 1, "Weakness to Cold": 3, "Fortify Arcana": 2},
        "Silkworm": { "Damage (Necrotic)": 3, "Damage (Psychic)": 4, "Resist Psychic": 3, "Resist Acid": 2, "Damage (Cold)": 1},
        "Silver Cap": { "Fortify Animal Handling": 3, "Damage (Force)": 3, "Resist Necrotic": 1, "Fortify Health": 2, "Damage (Necrotic)": 2},
        "Silver Crab Shell": { "Fortify Investigation": 3, "Damage (Psychic)": 4, "Damage (Psychic)": 2, "Weakness to Fire": 2, "Heal": 1},
        "Smiling Anemone": { "Resist Necrotic": 3, "Clairvoyance": 3, "Weakness to Slashing": 1, "Guided Strike": 2, "Waterbreathing": 2},
        "Speckled Gray Iris": { "Fortify Acrobatics": 4, "Resist Necrotic": 4, "Resist Poison": 2, "Guided Strike": 2, "Weakness to Poison": 3},
        "Spiny Raspberry": { "Fortify Survival": 5, "Resist Poison": 3, "Resist Psychic": 1, "Weakness to Lightning": 2, "Fortify Spell Strength": 2},
        "Starry Sage": { "Weakness to Force": 3, "Resist Fire": 4, "Fear": 1, "Fortify Spell Strength": 1, "Fortify Initiative": 2},
        "Stringy Aster": { "Fortify Perception": 4, "Fortify Charisma": 3, "Resist Force": 1, "Weakness to Poison": 1, "Fear": 1},
        "Striped Lova Flower": { "Heal": 4, "Weakness to Thunder": 2, "Resist Psychic": 1, "Fortify Animal Handling": 2, "Weakness to Cold": 3},
        "Teniarus Freesia": { "Heal": 4, "Fortify Strength": 4, "Weakness to Piercing": 1, "Fortify Health": 2, "Guided Strike": 2},
        "Thimbleberry": { "Resist Radiant": 3, "Fortify Performance": 4, "Resist Lightning": 2, "Resist Necrotic": 2, "Fortify Intelligence": 1},
        "Torch Flower": { "Weakness to Poison": 3, "Fortify Speed": 4, "Damage (Cold)": 1, "Weakness to Thunder": 2, "Weakness to Lightning": 1},
        "Tundra Tea": { "Invisibility": 3, "Resist Cold": 3, "Resist Lightning": 1, "Fortify Wisdom": 1, "Weakness to Slashing": 2},
        "Wax Myrtle": { "Resist Cold": 3, "Fortify Initiative": 4, "Fortify Armor": 2, "Fortify Constitution": 2, "Fortify Nature": 2},
        "White Fir Seeds": { "Damage (Cold)": 3, "Fortify Animal Handling": 4, "Weakness to Acid": 2, "Fortify Armor": 1, "Fortify Perception": 2},
        "White Poplar Leaves": { "Weakness to Necrotic": 4, "Regain Spell Slot": 4, "Fortify Wisdom": 2, "Waterbreathing": 1, "Weakness to Bludgeoning": 2},
        "White Tansy": { "Resist Cold": 3, "Fortify Initiative": 4, "Fortify Spell DC": 1, "Disguise Self": 1, "Fortify Acrobatics": 1},
        "Wild Rose": { "Weakness to Fire": 4, "Weakness to Bludgeoning": 4, "Weakness to Thunder": 1, "Fortify Constitution": 1, "Fear": 2},
        "Winter Currant": { "Fortify Medicine": 3, "Fortify Insight": 3, "Guided Strike": 2, "Damage (Psychic)": 1, "Damage (Lightning)": 1},
        "Yarrow Seeds": { "Damage (Cold)": 4, "Weakness to Piercing": 3, "Heal": 1, "Fortify Deception": 2, "Resist Radiant": 2},
        "Yeti Ants": { "Fortify Sleight of Hand": 4, "Fortify Nature": 7, "Fortify Investigation": 2, "Weakness to Acid": 3, "Fortify Intelligence": 3}
    };

const eleonUncommon =
    {
        "Banana Slug": { "Fortify Armor": 6, "Fortify Strength": 6, "Resist Force": 3, "Fortify Athletics": 1, "Resist Necrotic": 3},
        "Camphor Crystals": { "Regain Spell Slot": 6, "Fortify Acrobatics": 5, "Weakness to Lightning": 2, "Fortify History": 1, "Weakness to Fire": 1},
        "Cloak Salts": { "Weakness to Piercing": 6, "Fortify Strength": 6, "Fortify Initiative": 1, "Weakness to Lightning": 1, "Fortify Intelligence": 2},
        "Delfö Crystals": { "Damage (Force)": 5, "Disguise Self": 5, "Damage (Psychic)": 1, "Damage (Thunder)": 1, "Resist Fire": 1},
        "Fairie Slipper": { "Fortify Survival": 5, "Fortify Strength": 5, "Fortify History": 3, "Fortify Medicine": 2, "Resist Cold": 2},
        "Flaky Gypsum": { "Damage (Lightning)": 5, "Damage (Cold)": 6, "Fear": 2, "Clairvoyance": 1, "Weakness to Cold": 1},
        "Hanging Pesian Buds": { "Weakness to Thunder": 6, "Fortify Dexterity": 5, "Damage (Radiant)": 2, "Fortify Persuasion": 2, "Resist Acid": 1},
        "Hanging Soulsack": { "Fortify Spell Strength": 6, "Fortify Alchemy": 7, "Damage (Thunder)": 2, "Resist Radiant": 2, "Weakness to Bludgeoning": 1},
        "Jointed Larkspur": { "Weakness to Radiant": 6, "Resist Acid": 6, "Fortify Armor": 2, "Waterbreathing": 2, "Fortify Religion": 2},
        "Keelea Root": { "Fortify Initiative": 5, "Resist Fire": 4, "Fortify Investigation": 2, "Damage (Acid)": 1, "Damage (Lightning)": 1},
        "Maniara's Lace": { "Weakness to Cold": 6, "Resist Cold": 5, "Weakness to Fire": 1, "Fortify Acrobatics": 1, "Fortify Charisma": 1},
        "Misty Lavender": { "Fortify Alchemy": 5, "Fortify Constitution": 6, "Resist Lightning": 2, "Fortify Persuasion": 1, "Fortify Armor": 3},
        "Moon Fly": { "Fortify Health": 6, "Weakness to Radiant": 6, "Damage (Fire)": 1, "Fortify Performance": 1, "Disguise Self": 1},
        "Nipherelle Pollen": { "Fortify Health": 5, "Damage (Necrotic)": 5, "Fortify Deception": 1, "Fortify Alchemy": 2, "Damage (Force)": 2},
        "Noria Worm": { "Fortify Performance": 6, "Fortify Persuasion": 7, "Heal": 1, "Fortify Wisdom": 2, "Guided Strike": 2},
        "Patricandria's Bell": { "Weakness to Cold": 5, "Weakness to Poison": 6, "Damage (Radiant)": 3, "Clairvoyance": 2, "Resist Acid": 2},
        "Runeleaf Seed Pod": { "Fortify Intelligence": 7, "Weakness to Force": 5, "Fortify Sleight of Hand": 1, "Weakness to Piercing": 2, "Fortify Armor": 2},
        "Seelie Fairie Moss": { "Weakness to Lightning": 6, "Heal": 5, "Fortify Intimidation": 2, "Weakness to Poison": 3, "Damage (Fire)": 1},
        "Smoky Orchid": { "Fortify Persuasion": 6, "Fortify Deception": 6, "Resist Lightning": 1, "Damage (Thunder)": 2, "Fortify Charisma": 1},
        "Snowy Comfrey": { "Fortify Speed": 5, "Resist Acid": 6, "Damage (Psychic)": 1, "Fortify Stealth": 1, "Fortify Perception": 2},
        "Sorelenia Holly": { "Fortify Animal Handling": 7, "Invisibility": 6, "Fortify Perception": 2, "Guided Strike": 1, "Fortify Constitution": 1},
        "Sparkling Artesia": { "Fortify Speed": 6, "Fortify Charisma": 6, "Fear": 1, "Resist Poison": 2, "Weakness to Piercing": 2},
        "Stinging Frissey": { "Fortify Spell Strength": 5, "Weakness to Radiant": 5, "Damage (Radiant)": 1, "Fortify Arcana": 1, "Resist Lightning": 1},
        "Swan Egg": { "Fortify Initiative": 6, "Invisibility": 6, "Resist Acid": 1, "Resist Thunder": 1, "Resist Lightning": 2},
        "Teleona Foxglove": { "Damage (Radiant)": 5, "Fortify Athletics": 6, "Weakness to Psychic": 2, "Waterbreathing": 1, "Resist Force": 2},
        "Unseelie Farie Moss": { "Fortify Survival": 6, "Fortify Persuasion": 7, "Fortify Animal Handling": 2, "Resist Thunder": 1, "Damage (Psychic)": 1},
        "Wavy Chanterelle": { "Invisibility": 6, "Damage (Fire)": 5, "Fortify Perception": 1, "Resist Cold": 3, "Fortify Spell DC": 1},
        "White Truffle": { "Resist Radiant": 5, "Weakness to Psychic": 5, "Fortify Initiative": 1, "Guided Strike": 1, "Fortify Medicine": 2},
        "Whood Anemone": { "Resist Acid": 6, "Fortify Charisma": 6, "Weakness to Slashing": 3, "Regain Spell Slot": 2, "Resist Necrotic": 1},
        "Zenny Thistle": { "Disguise Self": 6, "Resist Psychic": 7, "Fortify Stealth": 3, "Weakness to Psychic": 1, "Guided Strike": 3}
    };

const eleonRare =
    {
        "Æther Moth": { "Fortify Dexterity": 9, "Fortify Health": 7, "Resist Poison": 4, "Damage (Psychic)": 5, "Fortify Perception": 1},
        "Argent Treeclack Wings": { "Damage (Radiant)": 6, "Fortify Deception": 8, "Fortify Medicine": 5, "Fortify Spell Strength": 4, "Fortify Medicine": 1},
        "Brassy Thorel Bulb": { "Fortify Survival": 8, "Damage (Radiant)": 7, "Damage (Radiant)": 5, "Damage (Psychic)": 5, "Fortify Dexterity": 2},
        "Dragon Ant Head": { "Damage (Cold)": 7, "Fortify Acrobatics": 8, "Fortify Intelligence": 5, "Fortify Investigation": 5, "Fortify Intelligence": 2},
        "Fairie Finger Orchid": { "Resist Force": 8, "Fear": 7, "Resist Thunder": 5, "Damage (Radiant)": 5, "Weakness to Acid": 1},
        "Phantom Orchid": { "Fortify Insight": 8, "Fortify Animal Handling": 7, "Weakness to Lightning": 5, "Weakness to Radiant": 5, "Weakness to Thunder": 1},
        "Powdered Zoranite": { "Fortify Performance": 7, "Fortify Intimidation": 7, "Fortify Wisdom": 4, "Resist Lightning": 4, "Fortify Religion": 1}
    };

const concentrates =
    {
    "Blood Resin": {"Fear": 7, "Necrotic Damage": 5},
    "Sal Folium": {"Heal": 5, "Fortify Medicine": 4},
    "Aqua Vitae": {"Fortify Charisma": 6, "Psychic Damage": 6},
    "Aqua Fortis": {"Acid Damage": 8, "Fortify Strength": 5},
    "Green Vitriol": {"Fortify Constitution": 6, "Resist Necrotic": 6},
    "Blue Vitriol": {"Cold Damage": 5, "Fortify Intelligence": 5},
    "Lux": {"Radiant Damage": 7, "Fortify Wisdom": 6},
    "Umbra": {"Invisibility": 8, "Fortify Dexterity": 6},
    "Red Vitriol": {"Fire Damage": 5, "Guided Strike": 5},
    "White Vitriol": {"Waterbreathing": 7, "Resist Force": 6},
    "Mana": {"Regain Spell Slot": 7, "Fortify Spellcasting": 7},
    "Anima": {"Fortify Constitution": 8, "Heal": 6}
  }
